// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYuxL2aUWkXejZXoiNNrRK7H4GOi5cw0M',
    appId: '1:832777697852:android:9eed2ab3224886097fa139',
    messagingSenderId: '832777697852',
    projectId: 'fir-pratice-96ab4',
    databaseURL: 'https://fir-pratice-96ab4-default-rtdb.firebaseio.com',
    storageBucket: 'fir-pratice-96ab4.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD49iXNUwyBH3zHc_lAhZMHSrGeYi-uBAw',
    appId: '1:832777697852:web:5b9ac612500dd53a7fa139',
    messagingSenderId: '832777697852',
    projectId: 'fir-pratice-96ab4',
    authDomain: 'fir-pratice-96ab4.firebaseapp.com',
    databaseURL: 'https://fir-pratice-96ab4-default-rtdb.firebaseio.com',
    storageBucket: 'fir-pratice-96ab4.appspot.com',
    measurementId: 'G-ED91JSW04W',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD49iXNUwyBH3zHc_lAhZMHSrGeYi-uBAw',
    appId: '1:832777697852:web:f89823e1a40bbf657fa139',
    messagingSenderId: '832777697852',
    projectId: 'fir-pratice-96ab4',
    authDomain: 'fir-pratice-96ab4.firebaseapp.com',
    databaseURL: 'https://fir-pratice-96ab4-default-rtdb.firebaseio.com',
    storageBucket: 'fir-pratice-96ab4.appspot.com',
    measurementId: 'G-RRFWSK53LM',
  );

}